In [1]:
import pandas as pd
pd.set_option('display.max_rows', 5)
import numpy as np
reviews = pd.read_csv("./Data/winemag-data-130k-v2.csv", index_col=0)

In [2]:
reviews.groupby('taster_twitter_handle').title.count()

taster_twitter_handle
@AnneInVino        3685
@JoeCz             5147
                   ...
@winewchristina       6
@worldwineguys     1005
Name: title, Length: 15, dtype: int64

In [3]:
best_rating_per_price = best_rating_per_price = reviews.groupby('price').points.max()
best_rating_per_price

price
4.0       86
5.0       87
          ..
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [4]:
price_extremes =reviews.groupby('variety').price.agg([min, max])
price_extremes

              min   max
variety
Abouriou     15.0  75.0
Agiorgitiko  10.0  66.0
...           ...   ...
Çalkarası    19.0  19.0
Žilavka      15.0  15.0

[707 rows x 2 columns]

In [26]:
sorted_varieties = price_extremes.sort_values(by=['min', 'max'], ascending=[False,False])
sorted_varieties

               min    max
variety
Ramisco      495.0  495.0
Terrantez    236.0  236.0
...            ...    ...
Zelen          NaN    NaN
Zierfandler    NaN    NaN

[707 rows x 2 columns]

In [29]:
reviewer_mean_ratings = reviews.groupby('taster_name').points.mean()
reviewer_mean_ratings

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
                        ...
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, Length: 19, dtype: float64

In [45]:
country_variety_counts = reviews.groupby(['country','variety'])['title'].count().sort_values(ascending=False)
country_variety_counts

country  variety
US       Pinot Noir            9885
         Cabernet Sauvignon    7315
                               ...
Mexico   Rosado                   1
Uruguay  White Blend              1
Name: title, Length: 1612, dtype: int64