In [30]:
import pandas as pd
pd.set_option('display.max_rows', 5)
import numpy as np
reviews = pd.read_csv("./Data/winemag-data-130k-v2.csv", index_col=0)

In [31]:
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [32]:
reviews.groupby('points').points.count()

points
80     397
81     692
      ...
99      33
100     19
Name: points, Length: 21, dtype: int64

In [33]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
       ...
99     44.0
100    80.0
Name: price, Length: 21, dtype: float64

In [34]:
reviews.loc[reviews['points'] ==80].sort_values('price')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
125826,Argentina,"While this smells floral and candied, the pala...",NaN,80,5.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Toca Diamonte 2010 Malbec (Mendoza),Malbec,Toca Diamonte
23437,Argentina,Candied plum and red berry aromas smell like r...,Estate Bottled,80,5.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Terrenal 2013 Estate Bottled Malbec (Mendoza),Malbec,Terrenal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117025,Portugal,A curious sauerkraut perfume leads to a hard e...,NaN,80,NaN,Lisboa,NaN,NaN,Roger Voss,@vossroger,Quinta do Pinto 2008 Touriga Nacional (Lisboa),Touriga Nacional,Quinta do Pinto
123541,Italy,"This Valpolicella blend opens with an aged, br...",Corte Antica,80,NaN,Veneto,Valpolicella Classico Superiore,NaN,NaN,NaN,Cantine Benedetti 2008 Corte Antica (Valpolic...,"Corvina, Rondinella, Molinara",Cantine Benedetti

In [35]:
reviews[['winery', 'title']].sort_values(by='winery')

      winery                                         title
63807  1+1=3  1+1=3 2008 Rosé Cabernet Sauvignon (Penedès)
55163  1+1=3                1+1=3 NV Brut Sparkling (Cava)
...      ...                                           ...
70504  Štoka            Štoka 2011 Grganja Vitovska (Kras)
10290  Štoka               Štoka 2009 Izbrani Teran (Kras)

[129971 rows x 2 columns]

In [36]:
reviews[['winery', 'title']].iloc[reviews['title'] == 0]

Empty DataFrame
Columns: [winery, title]
Index: []

In [37]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                          1+1=3 NV Rosé Sparkling (Cava)
10 Knots                 10 Knots 2010 Viognier (Paso Robles)
                                  ...
àMaurice    àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                         Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: str

In [38]:
reviews[['country', 'province', 'points']].sort_values('points').head(30)

       country          province  points
118056      US        California      80
35516       US        Washington      80
...        ...               ...     ...
34500    Chile  Colchagua Valley      80
109225      US        California      80

[30 rows x 3 columns]

In [39]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
...                                                                       ...
Uruguay   San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                          designation  points  price region_1  \
country   province
Argentina Mendoza Province           Nicasia Vineyard      97  120.0  Mendoza
          Other                               Reserva      95   90.0    Salta
...                                               ...     ...    ...      ...
Uruguay   San Jose           El Preciado Gran Reserva      87   50.0      NaN
          Uruguay           Blend 002 Limited Edition      91   22.0      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
...                             ...                ...                   ...
Uruguay   San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
...                                                                       ...
Uruguay   San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
...                                           ...                   ...
Uruguay   San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 11 columns]

In [40]:
reviews['price'].iloc[reviews['country']=='Argentina'].max()

np.float64(230.0)

In [41]:
reviews.groupby(['country']).price.agg([len, min, max])

            len   min    max
country
Argentina  3800   4.0  230.0
Armenia       2  14.0   15.0
...         ...   ...    ...
Ukraine      14   6.0   13.0
Uruguay     109  10.0  130.0

[43 rows x 3 columns]

In [50]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
...                          ...
Uruguay   San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [43]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([min])
countries_reviewed

                                                                          min
country   province
Argentina Mendoza Province  A baked, sweet, candied Malbec with a gritty, ...
          Other             A balanced Malbec with red fruit aromas and ju...
...                                                                       ...
Uruguay   San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           A dark, saturated color and stout aromas of he...

[425 rows x 1 columns]

In [44]:


mi = countries_reviewed.index
type(mi)

pandas.MultiIndex

In [45]:
mi

MultiIndex([('Argentina',  'Mendoza Province'),
            ('Argentina',             'Other'),
            (  'Armenia',           'Armenia'),
            ('Australia',   'Australia Other'),
            ('Australia',   'New South Wales'),
            ('Australia',   'South Australia'),
            ('Australia',          'Tasmania'),
            ('Australia',          'Victoria'),
            ('Australia', 'Western Australia'),
            (  'Austria',           'Austria'),
            ...
            (       'US',        'Washington'),
            (       'US', 'Washington-Oregon'),
            (  'Ukraine',           'Ukraine'),
            (  'Uruguay',         'Atlantida'),
            (  'Uruguay',         'Canelones'),
            (  'Uruguay',           'Juanico'),
            (  'Uruguay',        'Montevideo'),
            (  'Uruguay',          'Progreso'),
            (  'Uruguay',          'San Jose'),
            (  'Uruguay',           'Uruguay')],
           names=['country', 'province'], length=425)

In [46]:
countries_reviewed.reset_index()

,country,province,min
0,Argentina,Mendoza Province,"A baked, sweet, candied Malbec with a gritty, ..."
1,Argentina,Other,A balanced Malbec with red fruit aromas and ju...
...,...,...,...
423,Uruguay,San Jose,"Baked, sweet, heavy aromas turn earthy with ti..."
424,Uruguay,Uruguay,"A dark, saturated color and stout aromas of he..."

In [48]:
countries_reviewed.reset_index()

,index,country,province,min
0,0,Argentina,Mendoza Province,"A baked, sweet, candied Malbec with a gritty, ..."
1,1,Argentina,Other,A balanced Malbec with red fruit aromas and ju...
...,...,...,...,...
423,423,Uruguay,San Jose,"Baked, sweet, heavy aromas turn earthy with ti..."
424,424,Uruguay,Uruguay,"A dark, saturated color and stout aromas of he..."

In [51]:

countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

    country               province    len
179  Greece  Muscat of Kefallonian      1
192  Greece          Sterea Ellada      1
..      ...                    ...    ...
415      US             Washington   8639
392      US             California  36247

[425 rows x 3 columns]